[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_protocol = esptool
monitor_speed = 115200
upload_speed = 115200
upload_port = COM3
monitor_port = COM3
monitor_reconnect = yes
monitor_dtr = 1
monitor_rts = 0
monitor_filters = esp32_exception_decoder
lib_deps = 
    robtillaart/MCP23S17
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    adafruit/Adafruit NeoPixel
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1